version: '3.8'

services:
  university-etl:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=production
    restart: unless-stopped 